### ISSUE TITLE
ESP32 Support?

### ISSUE THREAD

**Issue by SlothCroissant** [ArduinoHannover/Pushover#13]
First off - GREAT work on this, it's been wildly helpful in some IoT projects I've been doing around the house! Using this is miles easier than manual POST requests.

I accidentally ordered some ESP32 boards instead of ESP8266, and have been able to get the project working on the platform. I simply had to remove this codeblock from [Pushover.cpp](https://github.com/ArduinoHannover/Pushover/blob/master/Pushover.cpp#L46)  (`setInsecure()` is not available on the ESP32 WifiClient.h, that I've found - I think #12 calls this out as well):

```
	if (_unsafe) {
		client.setInsecure();
	}
```

This results in a fully working Pushover client library for the ESP32 - simple as that (I think?)

Quick ask - is there anything else that would be a blocker on the ESP32 that I'm not thinking of? I'm admittedly fairly new at cpp and Arduino/ESP programming, so thought I'd ask here to see if I should be keeping anything in particular in consideration. Alternatively, maybe you can consider expanding support to ESP32 if it truly is this simple.

Thanks for all your work on this!

**Comment by brunojoyal** [comment]
Please see https://github.com/brunojoyal/PushoverESP32 for ESP32 support including HTTPS.
