### ISSUE TITLE
Return status is always 0

### ISSUE THREAD

**Issue by MirkoUgoliniDev** [ArduinoHannover/Pushover#6]
Hello,

I tested the library , but seems that the result is always 0 

I changenged that raw:

//return line.indexOf("\"status\":1") != -1;
return line.indexOf("200 OK") != -1;

now seems to work

Mirko

**Comment by jonmacd** [comment]
Thanks, was wondering the same thing.
This worked for me as well.

**Comment by teHwHoly** [comment]
Hi!

Was having similar issue, for now I'm just accepting both messages, because both of them are sent as response in irregular pattern:
return ( (line.indexOf("\"status\":1") != -1) || (line.indexOf("200 OK") != -1) );

**Comment by soundstorm** [comment]
Closed via #10
