### ISSUE TITLE
SSL connection certificate

### ISSUE THREAD

**Issue by teHwHoly** [ArduinoHannover/Pushover#8]
Hi!

Had problems, connecting to the API via secured connection.
I solved the issue by allowing the connection to have an insecure certificate:
... <boolean Pushover::send(void)>
...
	WiFiClientSecure client;
	client.setInsecure();
...
Now everything works fine for me.

**Comment by retry429** [comment]
Thanks @teHwHoly had the same problem too, you modification solved my problem too. Now I am able to send messages over pushover.

**Comment by soundstorm** [comment]
Closed via #11
